### PR TITLE
bufix for volume

### PR DESCRIPTION
**Pull request by mgh33**
I also removed several files from the git repository which do not belong into the repo (IMHO)

edit:
in the meantime I merged the changes from aluver into my branch

### CODE REVIEW

**Comment by aluver** [comment]
Hi, mgh33! Could you translate to german my strings in Settings for USB-DAC Volume, if they will be merged ever? I am translated your last added strings to russian already.

**Comment by mgh33** [comment]
here you are:
I merged your changes into my branch 
in the last commit I translated your strings :)

I guess you missed some strings from me ;)

**Comment by aluver** [comment]
Oh, yes. Thank you. Added allready. Please check again my pull request.

**Comment by mgh33** [comment]
Thank you very much 
I merged it into my branch

**Comment by aluver** [comment]
Where is petrows? People are waiting for release...

**Pull request merged**
